# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'React_Native_Filmes' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for React_Native_Filmes
  pod 'Firebase/Core'
  pod 'Firebase/Auth'

  target 'React_Native_FilmesTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'React_Native_Filmes-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for React_Native_Filmes-tvOS

  target 'React_Native_Filmes-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
